#!/usr/bin/env python
# -*- coding: utf-8 -*-


import requests # pip install requests


def weather():
    url = "http://wttr.in/Beijing?format=4"
    resp = requests.get(url)
    if len(resp.text) < 50:
        print(resp.text)
    else:
        print("")


if __name__ == "__main__":
    weather()
